apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: meureplicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
       app: web
    spec:
      containers:
        - name: conversaotemperatura
          image: rodrigotg/conversao-temperatura:v1
          ports:
            - containerPort: 8080